# Generated by Django 5.2.6 on 2025-09-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcounseling',
            name='father_phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='student_phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
