# Generated by Django 5.2.6 on 2025-09-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0002_alter_studentcounseling_father_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcounseling',
            name='father_phone',
            field=models.CharField(max_length=15),
        ),
    ]
