# Generated by Django 5.2.6 on 2025-09-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0003_alter_studentcounseling_father_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcounseling',
            name='roll_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='student_phone',
            field=models.CharField(max_length=15),
        ),
    ]
