# Generated by Django 5.2.6 on 2025-09-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0004_studentcounseling_roll_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcounseling',
            name='student_photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
    ]
