# Generated by Django 5.2.6 on 2025-09-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0005_studentcounseling_student_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcounseling',
            name='prizes_participations1',
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='counseling_date5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='counseling_date6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='prizes_participations6',
            field=models.TextField(blank=True, null=True),
        ),
    ]
