# Generated by Django 5.2.6 on 2025-09-24 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0006_remove_studentcounseling_prizes_participations1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcounseling',
            name='counselor_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='counselor_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='counselor_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counselor_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='counselor_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='director_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='director_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='director_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='director_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='hod_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='hod_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='hod_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='hod_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='incharge_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='incharge_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='incharge_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incharge_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='incharge_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='status',
            field=models.CharField(choices=[('raised', 'Raised'), ('counselor_accepted', 'Counselor Accepted'), ('counselor_rejected', 'Counselor Rejected'), ('incharge_accepted', 'Class Incharge Accepted'), ('incharge_rejected', 'Class Incharge Rejected'), ('hod_accepted', 'HOD Accepted'), ('hod_rejected', 'HOD Rejected'), ('director_accepted', 'Director Accepted'), ('director_rejected', 'Director Rejected')], default='raised', max_length=30),
        ),
    ]
