# Generated by Django 5.2.6 on 2025-09-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0007_studentcounseling_counselor_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcounseling',
            name='prize_file2',
            field=models.FileField(blank=True, null=True, upload_to='prize_files/'),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='prize_file3',
            field=models.FileField(blank=True, null=True, upload_to='prize_files/'),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='prize_file4',
            field=models.FileField(blank=True, null=True, upload_to='prize_files/'),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='prize_file5',
            field=models.FileField(blank=True, null=True, upload_to='prize_files/'),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='prize_file6',
            field=models.FileField(blank=True, null=True, upload_to='prize_files/'),
        ),
    ]
