# Generated by Django 5.2.6 on 2025-09-24 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0008_studentcounseling_prize_file2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcounseling',
            name='counseling_date1',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='counseling_description1',
        ),
    ]
