# Generated by Django 5.2.6 on 2025-09-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0009_remove_studentcounseling_counseling_date1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcounseling',
            name='prize_file2',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='prize_file3',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='prize_file4',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='prize_file5',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='prize_file6',
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='counseling_date1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='counseling_description1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
